### ISSUE TITLE
`super_resolution.py`train()中对aster和crnn的使用混淆

### ISSUE THREAD

**Issue by XDUcy** [lct1997/BasicSTISR#2]
[https://github.com/lct1997/BasicSTISR/blob/master/interfaces/super_resolution.py](https://github.com/lct1997/BasicSTISR/blob/master/interfaces/super_resolution.py)
第88行`aster, aster_info = self.CRNN_init()`，和`CRNN_init()`中都是对这两个名字（crnn和aster）的混用，我对本领域不是特别了解，请问是这两个名字实际指同一模型（但我阅读两篇文献时似乎并不相同），还是在此处有做相应改动？

如将88行这里变量名改成crnn，是不是更好理解一些。

我尚是初学者，您的代码相比原仓库已经相当简洁易懂，目前除了这个地方，没有别的难以理解的地方，实在是想不通，还望解答，非常感谢！

**Comment by lct1997** [comment]
> https://github.com/lct1997/BasicSTISR/blob/master/interfaces/super_resolution.py 第88行`aster, aster_info = self.CRNN_init()`，和`CRNN_init()`中都是对这两个名字（crnn和aster）的混用，我对本领域不是特别了解，请问是这两个名字实际指同一模型（但我阅读两篇文献时似乎并不相同），还是在此处有做相应改动？
> 
> 如将88行这里变量名改成crnn，是不是更好理解一些。
> 
> 我尚是初学者，您的代码相比原仓库已经相当简洁易懂，目前除了这个地方，没有别的难以理解的地方，实在是想不通，还望解答，非常感谢！

当实例化为aster时，它表示一个文本先验生成器CRNN，当实例化为crnn时，它是测试模型CRNN，怕混用所以我另起了名字用于区分。
